[package]
name = "saavi"
version = "0.1.2"
description = "Saavi — the friendliest face of GPG."
license = "MIT"
repository = "https://github.com/kaditham-technologies/saavi"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-http = "2"
serde = { version = "1", features = ["derive"] }

[profile.release]
lto = true
strip = true
